spring.application.name=Backend
spring.mongodb.uri=mongodb://localhost:27017/resumeBuilder

#spring.mail.host=
#spring.mail.port=
#spring.mail.username=
#spring.mail.password=
#spring.mail.properties.mail.smtp.auth=
#spring.mail.properties.mail.starttls.enable=
#spring.mail.protocol=
#spring.mail.properties.mail.smtp.from=

app.base.url=http://localhost:8080 