spring.application.name=Backend
spring.mongodb.uri=mongodb://localhost:27017/resumeBuilder

#for email service by brevo

#spring.mail.host=
#spring.mail.port=
#spring.mail.username=
#spring.mail.password=
#spring.mail.properties.mail.smtp.auth=
#spring.mail.properties.mail.starttls.enable=
#spring.mail.protocol=
#spring.mail.properties.mail.smtp.from=

#application info
app.base.url=http://localhost:8080 

#Cloudinary info for image storage
#cloudinary.cloud-name=
#cloudinary.api-key=
#cloudinary.api-secret=

#JWT Configuration

#jwt.secret=
#jwt.expiration=

#razorpay info
#razorpay.key.id=
#razorpay.key.secret=